### ISSUE TITLE
Create Installer Script

### ISSUE THREAD

**Issue by circa10a** [circa10a/Device-Monitor-Dashboard#2]
Should be able to:
 - Determine what web server is installed
 - clone in to /var/www/html/ or /usr/share/nginx/
 - chown to www-data
 - provide text based menu to add ip addresses/hostnames to txt file
 - configure cron according to user input choice of time frequency

**Comment by circa10a** [comment]
@loganoconnell  What do you think about this as a feature? That way one could issue a single curl command and install and configure the software.

Good job with the template BTW.

**Comment by loganoconnell** [comment]
I think that's a great feature idea! Much easier for those not-as-skilled Pi users. I'm not experienced with Bash scripting but we can look at something like PiHole's install script to get an idea.

**Comment by circa10a** [comment]
I have some pretty decent bash experience. I probably won't get to work on it until this weekend, but this would be a good opportunity for you to learn as well.(I mean, if you want to)

 Hint:exit codes are your friend in bash

**Comment by circa10a** [comment]
@loganoconnell  Got a working version. Could it be better? Always
