### ISSUE TITLE
Change log

### ISSUE THREAD

**Issue by lordlala** [circa10a/Device-Monitor-Dashboard#3]
Hi, are you able to include a change log with each release by chance?

Also, where on here could I request features? I'm not used to using Github so I apologize in advance. I wanted to know if there's a way to either include multiple tabs or at least have multiple circle/percentages. I want to have a different one for servers/services and routers, if that is possible.

I love your project by the way. Using this bad boy and loving it. Basic and straight forward.

**Comment by circa10a** [comment]
Sure. I usually leave a small description in the commits. To request new features, open an issue and label with "enhancement"

**Comment by circa10a** [comment]
I have began to include a changelog in the README.md
