### ISSUE TITLE
report.py and hostnames.txt path

### ISSUE THREAD

**Issue by BastienM** [circa10a/Device-Monitor-Dashboard#5]
Hi,

Would be great to implement an additional argument (eg. `report.py /path/to/file`) to specify where `report.py` should look for `hostnames.txt`.

This will enable further enhancements to the Docker image (entrypoint and provide an immutable image).

**Comment by circa10a** [comment]
This info is now stored in a database in this project - https://github.com/shaggyloris/simple-monitor
